"""
build_bundle.py
Bundles content/index.json and every subject listed in it into
content/data-bundle.js so the quiz works when index.html is opened
directly from disk (file://), where browsers block fetch().

Run after adding or editing any subject:
    python tools/build_bundle.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
SUBJECT_FILES = ("meta", "easy", "medium", "hard")


def iter_subject_ids(index):
    """Yields every subject id in Department -> Year -> Semester -> Subject order."""
    for dept in index.get("departments", []):
        for year in dept.get("years", []):
            for sem in year.get("semesters", []):
                for subject in sem.get("subjects", []):
                    yield subject["id"]


def main():
    index = json.loads((CONTENT / "index.json").read_text(encoding="utf-8"))
    subjects = {}
    missing = []

    for subject_id in dict.fromkeys(iter_subject_ids(index)):
        folder = CONTENT / "subjects" / subject_id
        try:
            subj_dict = {
                name: json.loads((folder / f"{name}.json").read_text(encoding="utf-8"))
                for name in SUBJECT_FILES
            }
            fc_path = folder / "flashcards.json"
            if fc_path.exists():
                subj_dict["flashcards"] = json.loads(fc_path.read_text(encoding="utf-8"))
            subjects[subject_id] = subj_dict
        except FileNotFoundError as err:
            missing.append(f"{subject_id}: {err.filename}")

    if missing:
        print("Missing subject files:\n  " + "\n  ".join(missing), file=sys.stderr)
        sys.exit(1)

    bundle = {"index": index, "subjects": subjects}
    out = CONTENT / "data-bundle.js"
    out.write_text(
        "// Auto-generated by tools/build_bundle.py - do not edit by hand.\n"
        "// Lets the quiz load content when index.html is opened via file://.\n"
        "window.APP_DATA_BUNDLE = " + json.dumps(bundle, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {out} with {len(subjects)} subject(s).")


if __name__ == "__main__":
    main()
